### ISSUE TITLE
[bug]: Unable to submit showcases

### ISSUE THREAD

**Issue by nataliasayang** [freesewing/freesewing#6855]
### What seems to be the problem? 🤔

When I submit a showcase post, the "Creating showcase post & pull request" toast notification appears but nothing else happens. No pull request is created.

### Additional context

I tried to submit two showcases. One had one JPG image (1.6 MB) and the other had one PNG image (3.4 MB). I am submitting on behalf of other users, and am signed in as myself (user ID 19867). All fields in the new showcase post form are filled out except there are no additional images.

**Comment by HaasJona** [comment]
This was discussed on Discord before: https://discord.com/channels/698854858052075530/1025804152628072509/threads/1249955833991663711

@bobgeorgethe3rd said it's already fixed, though.

**Comment by joostdecock** [comment]
This was broken because the backend's GitLab token expired. Which was fixed in https://github.com/freesewing/freesewing/issues/6832#issuecomment-2162871795

So if it does not work now, that's a different issue and we should look into that.
There's also been several showcase claims since, showing that the backend/github integration is ok.

That being said, if @nataliasayang can confirm it's still broken for her, we'll look into it.

**Comment by nataliasayang** [comment]
@HaasJona @joostdecock 

I acknowledged #6832 before submitting this ticket: https://discord.com/channels/698854858052075530/1148566982006931606/1250866344199458959

> Still unable to submit showcases. I thought https://github.com/freesewing/freesewing/issues/6832 might fix it but it seems to be something else. I'll submit a GitHub issue.

I just tried submitting a showcase again and it still does not work.

I have tried submitting these showcases a dozen times or so. If you or anyone else has successfully submitted a showcase in the last three days, please let me know what I should do differently.

**Comment by joostdecock** [comment]
Thank you @nataliasayang Turns out the token lacked permissions to create the merge request (I only tested the claim showcase thing, which only creates issues, so that worked fine :see_no_evil: )

I've fixed that and tested it: https://github.com/freesewing/freesewing/pull/6861

It's ok now. Closing.
